import { useState } from 'react';

const WORDS: Record<string,string> = {
  sie:'Вы / она / они', möchten:'хотеть', möchte:'хочет', einen:'один / какой-то', eine:'одна / какую-то', ein:'один / какой-то', der:'артикль', die:'артикль', das:'артикль', den:'артикль', dem:'артикль', ihr:'ваш / ваша / их', ihre:'ваша / их', ihrer:'вашей / их', ihnen:'им', ich:'я', wir:'мы', mein:'мой',
  kurs:'курс', kurse:'курсы', besuchen:'посещать', besucht:'посещает', tenniskurs:'курс тенниса', schreiben:'писать', schreibt:'пишет', an:'в / к', nach:'после / в', von:'от / из', aus:'из', bei:'у / при', für:'для / на', mit:'с', ohne:'без', über:'о / через', auf:'на', in:'в / на', im:'в', am:'в / на', zum:'к / для', zur:'к / в',
  sportverein:'спортивный клуб', warum:'почему', welchen:'какой / который', welchem:'какому', welcher:'какая / которая', tagen:'дни', tage:'дни', preis:'цена',
  freund:'друг', freundin:'подруга', freunde:'друзья', freunden:'друзьям', kollege:'коллега', kollegin:'коллега', karte:'открытка / карта', wann:'когда', kommen:'приходить / приезжать', kommt:'приходит / приезжает', wie:'как', reisen:'путешествовать / ехать', zusammen:'вместе', machen:'делать', macht:'делает', was:'что', wo:'где', wer:'кто', welche:'какие / которые',
  tochter:'дочь', sohn:'сын', kinder:'дети', kind:'ребёнок', krank:'больной', schule:'школа', fehlt:'отсутствует', fehlen:'отсутствовать', vom:'с / от', bis:'до', fragen:'спрашивать', fragt:'спрашивает', hausaufgaben:'домашние задания', information:'информация', informationen:'информация',
  september:'сентябрь', hamburg:'Гамбург', touristeninformation:'туристическая информация', museum:'музей', museen:'музеи', konzerte:'концерты', konzert:'концерт', hoteladressen:'адреса отелей', hotel:'отель', adressen:'адреса',
  computer:'компьютер', kaufen:'покупать', gekauft:'купленный', markus:'Маркус', bitten:'просить', hilfe:'помощь', zeit:'время', treffen:'встречаться', getroffen:'встретился', frau:'госпожа / женщина', herr:'господин / мужчина', eingeladen:'пригласил(а)', einladung:'приглашение', geburtstagsfeier:'празднование дня рождения', geburtstag:'день рождения', danken:'благодарить', danke:'спасибо', leider:'к сожалению', können:'мочь', kann:'может', können:'мочь', nicht:'не', wochenende:'выходные',
  notiz:'записка', morgen:'завтра', später:'позже', heute:'сегодня', arbeiten:'работать', arbeitet:'работает', länger:'дольше', juni:'июнь', nürnberg:'Нюрнберг', party:'вечеринка', freitag:'пятница', kleine:'маленькая', laden:'приглашать / загружать', einladen:'приглашать', beginnt:'начинается', beginnen:'начинаться', gäste:'гости', mitbringen:'приносить с собой',
  fotokurs:'фотокурс', volkshochschule:'народный университет / VHS', viel:'много / сколько', kostet:'стоит', kosten:'стоить', juli:'июль', dienstlich:'по работе', köln:'Кёльн', neuer:'новый', termin:'встреча / назначенный срок', august:'август', fernseher:'телевизор', internet:'интернет', verkäufer:'продавец', heißt:'называется / зовут', abholen:'забирать',
  anna:'Анна', tobias:'Тобиас', feiern:'праздновать', sommer:'лето', ferienjob:'работа на каникулах', café:'кафе', lohn:'зарплата', sonntag:'воскресенье', nachbar:'сосед', nachbarn:'соседи', entschuldigung:'извинение', entschuldigen:'извиняться', kaffee:'кофе', trinken:'пить', auto:'автомобиль', mieten:'арендовать', autovermietung:'прокат автомобилей', viele:'много',
  mittwoch:'среда', montag:'понедельник', schnell:'быстро', antworten:'отвечать', november:'ноябрь', münchen:'Мюнхен', theater:'театр', kino:'кино', wollten:'хотели', schwimmkurs:'курс плавания', schwimmen:'плавать', sportzentrum:'спортивный центр', anmelden:'регистрироваться', anmeldung:'регистрация', muss:'должен / нужно', müssen:'должны / нужно', man:'кто-то / человек', gehen:'идти', lehrerin:'учительница', hannover:'Ганновер', ankunft:'прибытие', uhr:'час', handy:'мобильный телефон', funktioniert:'работает',
  grillparty:'вечеринка с барбекю', wagner:'Вагнер', adresse:'адрес', uhrzeit:'время', malkurs:'курс рисования', malen:'рисовать', findet:'проходит', familie:'семья', schulz:'Шульц', allen:'всем', geht:'идёт / дела', dortmund:'Дортмунд', hotelpreisen:'ценах на отели', sehenswürdigkeiten:'достопримечательности', dresden:'Дрезден', oktober:'октябрь', stadtplan:'карта города', schlüssel:'ключ', geben:'давать', laptop:'ноутбук', garantie:'гарантия', picknick:'пикник', mehr:'больше', kursleiter:'руководитель курса', mai:'май', kulturprogramm:'культурная программа', stuttgart:'Штутгарт', april:'апрель', ausstellungen:'выставки', ausstellung:'выставка', probleme:'проблемы', problem:'проблема', englischkurs:'курс английского', englisch:'английский', erfurt:'Эрфурт', schreibtisch:'письменный стол', fischer:'Фишер', computergeschäft:'компьютерный магазин', krüger:'Крюгер', abendessen:'ужин', friseur:'парикмахер', friseursalon:'парикмахерский салон', haarschnitt:'стрижка', dienstag:'вторник', becker:'Беккер', oliver:'Оливер', bonn:'Бонн', nina:'Нина', gitarrenkurs:'курс игры на гитаре', gitarre:'гитара', hund:'собака', sehen:'видеть / посмотреть', mutter:'мама', deutschlehrer:'учитель немецкого', deutsch:'немецкий', fahren:'ехать', kleiderschrank:'шкаф для одежды', schrank:'шкаф',
  frankreich:'Франция', frankreichs:'Франции', lyon:'Лион', geboren:'родившийся / родилась', geburtsdatum:'дата рождения', geburtsort:'место рождения', vormittag:'утро', vormittags:'утром', morgens:'утром', gelernt:'учил / изучал', lernen:'учить / изучать', sprache:'язык', sprachen:'языки', muttersprache:'родной язык', anfänger:'начинающий', anfängerinnen:'начинающие (женщины)', kursbeginn:'начало курса', kursdauer:'продолжительность курса', kurszeit:'время занятий', fünf:'пять', fehlenden:'недостающие', informationen:'сведения / информация', formular:'формуляр / бланк', helfen:'помогать', freundschaft:'дружба',
  arztpraxis:'врачебный кабинет', patienteninformation:'информация для пациента', patientenkarte:'карта пациента', freund:'друг', vladimir:'Владимир', serjakov:'Серяков', hamburg:'Гамбург', reiseleiter:'экскурсовод', gestern:'вчера', grad:'градус', fieber:'температура / жар', arzt:'врач', besser:'лучше', versichert:'застрахован', krankenkasse:'медицинская страховка / касса', postleitzahl:'почтовый индекс', wohnort:'место жительства', alter:'возраст', beruf:'профессия', seit:'с', was:'что', fehlt:'не хватает / беспокоит', ihnen:'вам', datum:'дата', unterschrift:'подпись',
  handy:'мобильный телефон', gewinnspiel:'розыгрыш', karim:'Карим', müller:'Мюллер', drei:'три', jahre:'годы / лет', alt:'возрастом', autowerkstatt:'автомастерская', automechaniker:'автомеханик', noch:'ещё', kein:'никакой / нет', internet:'интернет', findet:'находит', teilnehmen:'участвовать', teilnahme:'участие', name:'имя', nachname:'фамилия', vorname:'имя', geschlecht:'пол', männlich:'мужской', weiblich:'женский', geburtsjahr:'год рождения', tätigkeit:'деятельность / работа', verheiratet:'женат / замужем', familienstand:'семейное положение', marke:'марка', nokia:'Nokia',
  ferienwohnung:'дом для отдыха / квартира для отдыха', familie:'семья', novak:'Новак', sommerferien:'летние каникулы', woche:'неделя', wochen:'недели', verbringen:'проводить', anreise:'приезд', abreise:'отъезд', personen:'человек / лица', schlafzimmer:'спальня', frühstück:'завтрак', buchen:'бронировать', haustier:'домашнее животное', vermieter:'арендодатель', reservierung:'бронирование', telefon:'телефон',
  volkshochschule:'народный университет', pavel:'Павел', kowalski:'Ковальски', tagsüber:'днём', lager:'склад', deshalb:'поэтому', abends:'вечером', abend:'вечер', september:'сентябрь', montags:'по понедельникам', mittwochs:'по средам', teilnehmen:'участвовать / посещать', bereits:'уже', email:'электронная почта', e:'э', mail:'почта', unterlagen:'материалы / документы', bekommen:'получать', bezahlt:'оплачен', bezahlt:'оплачен',
  fitnessstudio:'фитнес-клуб', fitplus:'FitPlus', anna:'Анна', weber:'Вебер', zieht:'переезжает', wohnung:'квартира', gleichzeitig:'одновременно', training:'тренировка', beginnen:'начинать', liebsten:'больше всего', fitness:'фитнес', montags:'по понедельникам', mittwochs:'по средам', monatlich:'ежемесячный', beitrag:'взнос / плата', höchstens:'максимум', euro:'евро', vertrag:'договор', mitglied:'член',
  stadtbibliothek:'городская библиотека', ausweis:'удостоверение / билет', daniel:'Даниэль', becker:'Беккер', neu:'новый', bücher:'книги', ausleihen:'брать напрокат / выдавать', neue:'новая', straße:'улица', hausnummer:'номер дома', rückfragen:'дополнительные вопросы', erreichen:'связаться', benutzt:'использует', gültig:'действительный', bis:'до',
  sprachschule:'языковая школа', abendkurs:'вечерний курс', elena:'Елена', martin:'Мартин', spanien:'Испания', muttersprache:'родной язык', bisher:'до сих пор', keinen:'никакой / ни одного', deshalb:'поэтому', anfängerkurs:'курс для начинающих', donnerstags:'по четвергам', unterricht:'занятия', unterrichtszeit:'время занятий',
  schwimmbad:'бассейн', kinderkurs:'детский курс', lukas:'Лукас', schmidt:'Шмидт', acht:'восемь', ferien:'каникулы', anfänger:'начинающий', noch:'ещё', nie:'никогда', mutter:'мама', samstags:'по субботам', begleiten:'сопровождать', notfall:'экстренный случай', erreichbar:'доступен / можно связаться',
  zahnarztpraxis:'стоматологическая клиника', termin:'приём / назначенная встреча', sofia:'София', keller:'Келлер', zwei:'два', tagen:'дня', starke:'сильная', zahnschmerzen:'зубная боль', möglichst:'по возможности', schnell:'быстро', dienstag:'вторник', versicherung:'страховка', rückrufen:'перезвонить',
  reisebüro:'туристическое агентство', tagesfahrt:'однодневная поездка', thomas:'Томас', klein:'маленький / Кляйн', zwei:'два', freunden:'друзьями', reise:'поездка', reisedatum:'дата поездки', bus:'автобус', fährt:'едет / отправляется', abfahrt:'отправление', rückfahrt:'обратная поездка', geplant:'запланирован', bahnhof:'вокзал', eingang:'вход', west:'запад', buchung:'бронирование', anmelden:'оформлять / регистрировать',
  kindergarten:'детский сад', sonnenschein:'солнечный свет', emma:'Эмма', berger:'Бергер', täglich:'ежедневно', betreut:'присматривают / находится под присмотром', allergien:'аллергии', allergie:'аллергия', notfallkontakt:'контакт на случай экстренной ситуации', kontakt:'контакт',
  musikschule:'музыкальная школа', klavierkurs:'курс фортепиано', jonas:'Йонас', fischer:'Фишер', neunzehn:'девятнадцать', zum:'к', ersten:'первый', instrument:'инструмент', klavier:'фортепиано', niveau:'уровень', regelmäßig:'регулярно', benötigt:'нуждается / требуется', erste:'первый',
  fahrschule:'автошкола', führerschein:'водительские права', klasse:'категория / класс', laura:'Лаура', könig:'Кёниг', herbst:'осень', normales:'обычный', auto:'автомобиль', theorie:'теория', nächste:'следующий', telefon:'телефон',
  postfiliale:'почтовое отделение', paketabholung:'получение посылки', mehmet:'Мехмет', yilmaz:'Йылмаз', wartet:'ждёт', paket:'посылка', paketnummer:'номер посылки', filiale:'отделение', personalausweis:'удостоверение личности', abholtag:'день получения',
  schülerausweis:'школьное удостоверение', max:'Макс', hoffmann:'Хоффман', goethe:'Гёте', klasse:'класс', schüler:'ученик', wohnt:'живёт', aktuell:'актуальный', foto:'фотография', abgeben:'сдать / предоставить',
  universität:'университет', mensakarte:'карта столовой', julia:'Юлия', roth:'Рот', studiert:'изучает / учится', germanistik:'германистика', matrikelnummer:'номер студента', studiengang:'специальность', allergien:'аллергии', guthaben:'баланс / кредит', abholung:'получение', mensa:'столовая', aufladen:'пополнить',
  arbeitsagentur:'служба занятости', beratung:'консультация', ahmed:'Ахмед', hassan:'Хассан', koch:'повар', sucht:'ищет', stelle:'место работы / должность', kundennummer:'номер клиента', grund:'причина', arbeitssuche:'поиск работы',
  wohnungsbesichtigung:'просмотр квартиры', nina:'Нина', petrova:'Петрова', interessiert:'интересуется', zweizimmerwohnung:'двухкомнатная квартира', vermieter:'арендодатель', besichtigungstermin:'время просмотра', allein:'один / одна', email:'электронная почта', telefonnummer:'номер телефона',
  waschsalon:'прачечная', kundenkarte:'клиентская карта', stefan:'Стефан', wolf:'Вольф', parkstraße:'Паркштрассе', parkweg:'Парковая улица', waschprogramm:'программа стирки', großwäsche:'большая стирка', karte:'карта', gelten:'действовать', monatspreis:'месячная цена',
  konzert:'концерт', kartenbestellung:'заказ билетов', nadine:'Надин', bauer:'Бауэр', sommermusik:'летняя музыка', sitzplatz:'сидячее место', sitzplätze:'сидячие места', abendkasse:'вечерняя касса', karten:'билеты', anzahl:'количество', kategorie:'категория',
  bäckerei:'пекарня', vorbestellung:'предварительный заказ', peter:'Петер', lang:'длинный / Ланг', vollkornbrot:'цельнозерновой хлеб', vollkornbrote:'цельнозерновой хлеб', apfelkuchen:'яблочный пирог', bestellung:'заказ', hafenstraße:'Хафенштрассе', änderung:'изменение', telefonisch:'по телефону',
  tierarzt:'ветеринар', anmeldung:'регистрация', maria:'Мария', stein:'Штайн', katze:'кошка', mimi:'Мими', impfung:'прививка', besitzerin:'владелица', tier:'животное',
  museum:'музей', gruppenbesuch:'посещение группой', eva:'Ева', sommer:'Зоммер / лето', gruppe:'группа', führung:'экскурсия', sprache:'язык', deutsch:'немецкий', stattfinden:'состояться / проходить',
  fußball:'футбол', robert:'Роберт', maier:'Майер', sportart:'вид спорта', geburtsjahr:'год рождения', trainingstag:'день тренировки', trainingszeit:'время тренировки', trikotgröße:'размер футболки', größe:'размер',
  café:'кафе', tischreservierung:'бронирование столика', sara:'Сара', ali:'Али', samstag:'суббота', samstags:'по субботам', freunden:'друзьями', insgesamt:'всего', reservierung:'бронирование', bestätigung:'подтверждение', innenbereich:'внутренняя зона', bereich:'зона', innen:'внутри',
  schlüsseldienst:'слесарная служба', auftrag:'заказ', klaus:'Клаус', richter:'Рихтер', verloren:'потерял', wohnungsschlüssel:'ключ от квартиры', gartenstraße:'Гартенштрассе', monteur:'мастер', rechnung:'счёт', bar:'наличными', bezahlen:'оплачивать',
  schuhgeschäft:'обувной магазин', bestellung:'заказ', lisa:'Лиза', wagner:'Вагнер', modell:'модель', city:'город', runner:'бегун', farbe:'цвет', schwarz:'чёрный', paar:'пара', geschäft:'магазин', abholen:'забирать',
  campingplatz:'кемпинг', reservierung:'бронирование', familie:'семья', fischer:'Фишер', zelt:'палатка', anfang:'начало', anfang:'начало', reisen:'путешествовать', platz:'место', zeltplatz:'место для палатки', auto:'автомобиль',
  abends:'вечером', abend:'вечер', wieder:'снова / обратно', bald:'скоро', schon:'уже', denn:'ведь / потому что', aber:'но', und:'и', oder:'или', auch:'также', noch:'ещё', sehr:'очень', nur:'только', zu:'к / слишком', dann:'тогда', jetzt:'сейчас',
  aufgabe:'задание', helfen:'помогать', freundin:'подруга', freund:'друг', schreiben:'писать', fehlenden:'недостающие', fünf:'пять', informationen:'сведения / информация', formular:'формуляр / бланк', ausfüllen:'заполнять', angabe:'сведения', angaben:'сведения'
};

function normalize(word:string){return word.toLowerCase().replace(/[.,!?;:()„“\"'–—]/g,'').trim();}

export function GermanWordTooltip({text}:{text:string}){
  const [open,setOpen]=useState<string|null>(null);
  return <span className="inline leading-7">{text.split(/(\s+)/).map((token,i)=>{
    if(/^\s+$/.test(token)) return <span key={i}>{token}</span>;
    const clean=normalize(token), translation=WORDS[clean];
    if(!translation) return <span key={i}>{token}</span>;
    const id=`${i}-${clean}`, active=open===id;
    return <span key={i} className="relative inline-block">
      <button type="button" aria-label={`Перевод: ${clean}`} onClick={()=>setOpen(active?null:id)} onMouseEnter={()=>setOpen(id)} onMouseLeave={()=>setOpen(null)} className="cursor-help rounded px-0.5 underline decoration-dotted decoration-slate-400 underline-offset-2 hover:bg-sky-50">{token}</button>
      {active&&<span className="pointer-events-none absolute bottom-[calc(100%+6px)] left-1/2 z-30 w-max max-w-[220px] -translate-x-1/2 rounded-lg bg-slate-900 px-2.5 py-1.5 text-xs font-medium leading-4 text-white shadow-lg">{translation}</span>}
    </span>;
  })}</span>;
}
